# Load default processing options
imports:
    - { resource: "EXT:project/config/rte/imports/processing.yml" }
    - { resource: "EXT:project/config/rte/imports/base.yml" }
    - { resource: "EXT:project/config/rte/imports/plugins.yml" }

# Add configuration for the editor for any configuration
# For complete documentation see http://docs.ckeditor.com/#!/api/CKEDITOR.config
editor:
    config:
        format_tags: "p"

        stylesSet: []

        toolbarGroups:
          - { name: styles, groups: [ format ] }
          - { name: paragraph, groups: [ list, align ] }
          - { name: basicstyles, groups: [ basicstyles, cleanup ] }
          - { name: links, groups: [ links ] }
          - { name: clipboard, groups:  [ undo, clipboard ] }
          - { name: document, groups: [ mode ] }

        removeButtons:
          - Anchor
          - Italic
          - Underline
          - Strike
          - Superscript
          - Subscript
          - Styles

        justifyClasses:
          - text-left
          - text-center
          - text-right
          - text-justify

        extraPlugins:
          - justify
